baseURL = 'https://penne.blog/'
languageCode = 'en-us'
title = 'Sages Blog'
defaultContentLanguage = 'en'
theme = 'zen'

defaultContentLanguageInSubdir = true

[taxonomies]
  category = 'categories'
  tag = 'tags'
  author = 'author'

[languages]
  [languages.en]
    contentDir = 'content/en-US'
    languageName = 'English'
    weight = 10
    disabled = false

  [languages.zh]
    contentDir = 'content/zh'
    languageName = '简体中文'
    weight = 20
    disabled = false
